### ISSUE TITLE
requirements title, 

### ISSUE THREAD

**Issue by itsweekly** [b4am/Stanford#2]
TIME, OS, ETC.. are included in python. it spits out errors even with the correct libraries. (corrected code)

@echo off
python -m pip install pystyle
python -m pip install pystyle==1.1
python -m pip install requests==2.27.1
python -m pip install discord
python -m pip install requests
python -m pip install colorama

**Comment by underagent** [comment]
eeh idc lol kids should figure it out them self but thx for your time lol.

**Comment by itsweekly** [comment]
the whole thing is broken though

**Comment by underagent** [comment]
no lol it works
