### ISSUE TITLE
Slow nuker

### ISSUE THREAD

**Issue by KDot227** [b4am/Stanford#3]

**Comment by b4am** [comment]
ong i didnt ask

**Comment by KDot227** [comment]
> ong i didnt ask

still slow

**Comment by b4am** [comment]
> > ong i didnt ask
> 
> still slow

ok idrc lol

**Comment by KDot227** [comment]
> > > ong i didnt ask
> > 
> > 
> > still slow
> 
> ok idrc lol

Somali Nuker V2 on top

**Comment by KDot227** [comment]
and batch token grabber

**Comment by b4am** [comment]
> > > > ong i didnt ask
> > > 
> > > 
> > > still slow
> > 
> > 
> > ok idrc lol
> 
> Somali Nuker V2 on top

ass but ok have made/saw better ones lol

**Comment by b4am** [comment]
> 

bro came here to promote his own shit LOL

**Comment by KDot227** [comment]
> > > > > ong i didnt ask
> > > > 
> > > > 
> > > > still slow
> > > 
> > > 
> > > ok idrc lol
> > 
> > 
> > Somali Nuker V2 on top
> 
> ass but ok have made/saw better ones lol

u cant really make it better in py 💀

**Comment by KDot227** [comment]
> > 
> 
> bro came here to promote his own shit LOL

stay mad

**Comment by b4am** [comment]
> > > > > > ong i didnt ask
> > > > > 
> > > > > 
> > > > > still slow
> > > > 
> > > > 
> > > > ok idrc lol
> > > 
> > > 
> > > Somali Nuker V2 on top
> > 
> > 
> > ass but ok have made/saw better ones lol
> 
> u cant really make it better in py 💀

more advenced lol + ur shit is slow lol

**Comment by b4am** [comment]
> > > 
> > 
> > 
> > bro came here to promote his own shit LOL
> 
> stay mad

😆 lmfao funny how u came here to trash talk and saying im mad

**Comment by KDot227** [comment]
> > > > > > > ong i didnt ask
> > > > > > 
> > > > > > 
> > > > > > still slow
> > > > > 
> > > > > 
> > > > > ok idrc lol
> > > > 
> > > > 
> > > > Somali Nuker V2 on top
> > > 
> > > 
> > > ass but ok have made/saw better ones lol
> > 
> > 
> > u cant really make it better in py 💀
> 
> more advenced lol + ur shit is slow lol

Whats more advanced 😭 + u literially cant make it any faster 💀 and ik ur ass aint test it

**Comment by KDot227** [comment]
> > > > 
> > > 
> > > 
> > > bro came here to promote his own shit LOL
> > 
> > 
> > stay mad
> 
> 😆 lmfao funny how u came here to trash talk and saying im mad

yuh cause u mad

**Comment by b4am** [comment]
> > > > > 
> > > > 
> > > > 
> > > > bro came here to promote his own shit LOL
> > > 
> > > 
> > > stay mad
> > 
> > 
> > 😆 lmfao funny how u came here to trash talk and saying im mad
> 
> yuh cause u mad

i aint, only u a random & prob a 12 y.o that pasted shit and tryna promote it everywhere lol

**Comment by KDot227** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > bro came here to promote his own shit LOL
> > > > 
> > > > 
> > > > stay mad
> > > 
> > > 
> > > 😆 lmfao funny how u came here to trash talk and saying im mad
> > 
> > 
> > yuh cause u mad
> 
> i aint, only u a random & prob a 12 y.o that pasted shit and tryna promote it everywhere lol

my ass just turned 16 and I made all that shit from scratch u can join cheataway and ill have kids vouch for me but ai

**Comment by KDot227** [comment]
I added yo ass cuz
